### ISSUE TITLE
[Missing SNMP Polling Profile] Synology DS1512+

### ISSUE THREAD

**Issue by AlanAvins** [kentik/snmp-profiles#319]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Synology

Device Model: DS1512+ (DSM 6.2.4)

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.8072.3.2.10

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

.1.3.6.1.4.1.6574.1 synoSystem 
.1.3.6.1.4.1.6574.2 synoDisk
.1.3.6.1.4.1.6574.3 synoRaid
.1.3.6.1.4.1.6574.4 synoUPS 
.1.3.6.1.4.1.6574.5 synologyDiskSMART
.1.3.6.1.4.1.6574.6 synologyService
.1.3.6.1.4.1.6574.101 storageIO
.1.3.6.1.4.1.6574.102 spaceIO
.1.3.6.1.4.1.6574.103 flashCache
.1.3.6.1.4.1.6574.104 synologyiSCSILUN
.1.3.6.1.4.1.6574.105 synologyEbox
.1.3.6.1.4.1.6574.106 synologyHA

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/AlanAvins/f86db9d4f6c44c4a80a1e2d464325f31
Official Synology MIB Files: [Synology_MIB_File.zip](https://github.com/kentik/snmp-profiles/files/8770547/Synology_MIB_File.zip)
Official Synology MIB Guide: https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@AlanAvins - this is addressed in PR #322 ; note that because Synology is using the Net-SNMP SysOID for generic Linux servers on this device, you will need to [manually override the config file](https://docs.newrelic.com/docs/network-performance-monitoring/troubleshooting/snmp-discovery-unexpected-profile#net-snmp) for ktranslate. 

ex:
```yaml
devices:
  synologyNAS_192.168.0.22:
    ...
    mib_profile: "!disk_station.yml"
...
global:
  ...
  mibs_enabled:
  - HOST-RESOURCES-MIB
  - SYNOLOGY-DISK-MIB
  - SYNOLOGY-GPUINFO-MIB
  - SYNOLOGY-RAID-MIB
  - SYNOLOGY-SERVICES-MIB
  - SYNOLOGY-SMART-MIB
  - SYNOLOGY-SPACEIO-MIB
  - SYNOLOGY-STORAGEIO-MIB
  - SYNOLOGY-SYSTEM-MIB
  - UCD-SNMP-MIB
  ...
```
