### ISSUE TITLE
Feature: Profile should let us know about computed values

### ISSUE THREAD

**Issue by Mesverrum** [kentik/snmp-profiles#382]
As I was explaining the profiles to an internal user I realized that the only way to know about any of the computed or hard coded values is to dig in the source of ktranslate or rely on institutional memory.  Can we determine a syntax or pattern for how we would expose those within the profile itself as a form of end user documentation.  We could just get into a pattern of commenting them into the files

I'm imagining something like:

```
...
metrics:
  - MIB: IF-MIB
    table:
      OID: 1.3.6.1.2.1.2.2
      name: ifTable
    symbols:
      # Faster polling to support anomaly detection
      # The total number of octets received on the interface, including framing characters. This object is a 64-bit version of ifInOctets.
      # Combines with sysUpTime and ifHCInOctets to compute IfInUtilization
      - name: ifHCInOctets
        OID: 1.3.6.1.2.1.31.1.1.1.6
        poll_time_sec: 60
...
    metric_tags:
      # An estimate of the interface's current bandwidth in units of 1,000,000 bits per second.
      # Combines with sysUpTime and ifHCInOctets to compute IfInUtilization
      # Combines with sysUpTime and ifHCOutOctets to compute IfOutUtilization
      - tag: if_Speed
        column:
          name: ifHighSpeed
          OID: 1.3.6.1.2.1.31.1.1.1.15
```
