### ISSUE TITLE
Brocade SW FC Port Stats

### ISSUE THREAD

**Issue by ayounas** [kentik/snmp-profiles#386]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Brocade

Device Model: Connectrix ED-DCX6-8B

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.1588.2.1.1.166

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - I can see there is already a profile for brocade and provides traffic related metrics but we are looking for FC port error metrics from below table. 
 -  SW-MIB::swFCPortTable  - 1.3.6.1.4.1.1588.2.1.1.1.6.2 (all fc port related metrics)
 -  
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

> gist only for relevant OID as brocade profile already exists and only need to add fibre channel related metrics especially errors

Gist Link: https://gist.github.com/ayounas/a2e7f2e1555c22168279ee216620d471

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by ayounas** [comment]
Existing profile : https://github.com/kentik/snmp-profiles/tree/main/profiles/kentik_snmp/brocade

**Comment by thezackm** [comment]
@ayounas - can you identify which metrics from that table in particular you are looking for? there are >30 columns per row shown on your provided walk results; from a glance these seem to be the ones that show some sort of performance metric in a gauge or counter value:

```yaml
# This object counts the number of (Fibre Channel) frames that the port has transmitted.
name: swFCPortTxFrames
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.13

# This object counts the number of (Fibre Channel) frames that the port has received.
name: swFCPortRxFrames
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.14

# This object counts the number of Class 2 frames that the port has received.
name: swFCPortRxC2Frames
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.15

# This object counts the number of Class 3 frames that the port has received.
name: swFCPortRxC3Frames
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.16

# This object counts the number of Link Control frames that the port has received.
name: swFCPortRxLCs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.17

# This object counts the number of Multicast frames that the port has received.
name: swFCPortRxMcasts
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.18

# This object counts the number of times when RDYs exceeds the frames received.
name: swFCPortTooManyRdys
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.19

# This object counts the number of times when the transmit credit has reached zero.
name: swFCPortNoTxCredits
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.20

# This object counts the number of encoding error or disparity error inside frames received.
name: swFCPortRxEncInFrs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.21

# This object counts the number of CRC errors detected for frames received.
name: swFCPortRxCrcs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.22

# This object counts the number of truncated frames that the port has received.
name: swFCPortRcTruncs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.23

# This object counts the number of received frames that are too long.
name: swFCPortRxTooLongs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.24

# This object counts the number of received frames that have bad EOF delimiter.
name: swFCPortRxBadEofs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.25

# This object counts the number of encoding error or disparity error outside frames received.
name: swFCPortRxEncOutFrs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.26

# This object counts the number of invalid Ordered Sets received.
name: swFCPortRxBadOs
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.27

# This object counts the number of Class 3 frames that the port has discarded.
name: swFCPortC3Discards
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.28

# This object counts the number of Multicast frames that has been timed out.
name: swFCPortMcastTimedOuts
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.29

# This object counts the number of Multicast frames that has been transmitted.
name: swFCPortTxMcasts
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.30

# This object counts the number of Loop Initializations that has been initiated by loop devices attached.
name: swFCPortLipIns
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.31

# This object counts the number of Loop Initializations that has been initiated by the port.
name: swFCPortLipOuts
OID: 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.32
```
